id: 'early_evening'
alias: Дом - Ранний вечер
description: ""
mode: single
triggers:
  - entity_id:
      - sensor.system_time_of_day_detailed
    to: early_evening
    trigger: state
conditions: []
actions:
  - action: light.turn_on
    metadata: {}
    data:
      transition: 3
      brightness_pct: 50
      kelvin: 4520
    target:
      device_id:
        - 96e1548acb880416f78bfe965e06461c
        - fc3c718cfb9df856ba26b49245cc78d2
        - e30a6cb4926e177593271f2c834bb909
        - 774e3c5cb748176992f7bc5a59199d95
  - action: light.turn_on
    metadata: {}
    data:
      effect: "Warm Waves"
    target:
      device_id: f2653fddc378327eff1438e10e5b985d