id: 'early_morning'
alias: Дом - Раннее утро
description: ""
mode: single
triggers:
  - entity_id:
      - sensor.system_time_of_day_strict
    to: "6"
    trigger: state
conditions: []
actions:
  - type: turn_on
    device_id: 0a5bd757648d4752cbe403817b630586
    entity_id: fee8218f970f4a507d14c4ce28cf0fe9
    domain: light
  - action: light.turn_on
    metadata: {}
    data:
      transition: 3
      brightness_pct: 70
      kelvin: 4500
    target:
      device_id:
        - fc3c718cfb9df856ba26b49245cc78d2
