id: 'early_morning'
alias: Дом - Раннее утро
description: ""
mode: single
triggers:
  - entity_id:
      - sensor.system_time_of_day_strict
    to: "6"
    trigger: state
conditions: []
actions:
  - type: turn_on
    device_id: 0a5bd757648d4752cbe403817b630586
    entity_id: fee8218f970f4a507d14c4ce28cf0fe9
    domain: light
  - action: yeelight.set_color_temp_scene
    metadata: {}
    data:
      kelvin: 3500
      brightness: 70
    target:
      device_id: fc3c718cfb9df856ba26b49245cc78d2