id: "late_evening"
alias: Дом - Поздний вечер
description: ""
mode: single
trigger:
  - platform: state
    entity_id:
      - sensor.system_time_of_day_strict
    to: "20"
conditions: []
actions:
  - type: turn_on
    device_id: 0a5bd757648d4752cbe403817b630586
    entity_id: fee8218f970f4a507d14c4ce28cf0fe9
    domain: light
  - type: turn_on
    device_id: 75739e28167cd8c27f94738c4e62d1b1
    entity_id: 62e676dd0b82493a035a731d979e71c5
    domain: light
  - delay:
      hours: 0
      minutes: 0
      seconds: 20
      milliseconds: 0
  - action: yeelight.set_color_temp_scene
    metadata: {}
    data:
      kelvin: 4500
      brightness: 20
    target:
      device_id:
        - 96e1548acb880416f78bfe965e06461c
        - fc3c718cfb9df856ba26b49245cc78d2
  - action: light.turn_on
    metadata: {}
    data:
      effect: Glimmer
    target:
      device_id: f2653fddc378327eff1438e10e5b985d