id: 'late_morning'
alias: Дом - Позднее утро
description: ""
mode: single
triggers:
  - entity_id:
      - sensor.system_time_of_day_strict
    to: "10"
    trigger: state
conditions: []
actions:
  - type: turn_on
    device_id: 0a5bd757648d4752cbe403817b630586
    entity_id: fee8218f970f4a507d14c4ce28cf0fe9
    domain: light
  - delay:
      hours: 0
      minutes: 0
      seconds: 20
      milliseconds: 0
  - action: light.turn_on
    metadata: {}
    data:
      transition: 3
      brightness_pct: 40
      kelvin: 5500
    target:
      device_id:
        - fc3c718cfb9df856ba26b49245cc78d2
  - action: light.turn_on
    metadata: {}
    data:
      effect: Sahara Night
    target:
      device_id: f2653fddc378327eff1438e10e5b985d
  - delay:
      hours: 0
      minutes: 30
      seconds: 0
      milliseconds: 0
  - action: yeelight.set_color_temp_scene
    metadata: {}
    data:
      kelvin: 5500
      brightness: 80
    target:
      device_id: fc3c718cfb9df856ba26b49245cc78d2