id: 'late_morning'
alias: Дом - Позднее утро
description: ""
mode: single
triggers:
  - entity_id:
      - sensor.system_time_of_day_detailed
    to: late_morning
    trigger: state
conditions: []
actions:
  - type: turn_on
    device_id: 0a5bd757648d4752cbe403817b630586
    entity_id: fee8218f970f4a507d14c4ce28cf0fe9
    domain: light
  - action: light.turn_on
    metadata: {}
    data:
      transition: 3
      brightness_pct: 100
      kelvin: 6500
    target:
      device_id:
        - fc3c718cfb9df856ba26b49245cc78d2
  - action: light.turn_on
    metadata: {}
    data:
      transition: 3
      brightness_pct: 50
      kelvin: 4500
    target:
      device_id:
        - 96e1548acb880416f78bfe965e06461c