id: "late_evening"
alias: Дом - Поздний вечер
description: ""
mode: single
trigger:
  - platform: state
    entity_id:
      - sensor.system_time_of_day_detailed
    to: "late_evening"
conditions: []
actions:
  - action: light.turn_on
    metadata: {}
    data:
      transition: 3
      brightness_pct: 30
      kelvin: 4520
    target:
      device_id:
        - 96e1548acb880416f78bfe965e06461c
        - fc3c718cfb9df856ba26b49245cc78d2
  - action: light.turn_on
    metadata: {}
    data:
      effect: "Glimmer"
    target:
      device_id: f2653fddc378327eff1438e10e5b985d
