id: "night_time"
alias: Дом - Ночное время
description: ""
triggers:
  - entity_id:
      - sensor.system_time_of_day_strict
    to: "23"
    trigger: state
condition: []
action:
  - action: input_boolean.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.rebenok_spit
  - type: turn_on
    device_id: 0a5bd757648d4752cbe403817b630586
    entity_id: fee8218f970f4a507d14c4ce28cf0fe9
    domain: light
  - delay:
      hours: 0
      minutes: 0
      seconds: 20
      milliseconds: 0
  - if:
      - condition: device
        type: is_off
        device_id: fc3c718cfb9df856ba26b49245cc78d2
        entity_id: b7959698f19f33fb80b13d707eda1af6
        domain: light
    then:
      - action: yeelight.set_mode
        metadata: {}
        data:
          mode: moonlight
        target:
          device_id: fc3c718cfb9df856ba26b49245cc78d2
  - action: light.turn_off
    metadata: {}
    data:
      transition: 3
    target:
      device_id: 96e1548acb880416f78bfe965e06461c
  - action: light.turn_on
    metadata: {}
    data:
      effect: "Fireflies"
    target:
      device_id: f2653fddc378327eff1438e10e5b985d
  - device_id: fb7478e46ebb1c6857c3f498301f4381
    domain: humidifier
    entity_id: 363affaee91aeb03abff603b1303a63a
    type: set_mode
    mode: Strong
  - delay:
      hours: 0
      minutes: 15
      seconds: 0
      milliseconds: 0
  - device_id: fb7478e46ebb1c6857c3f498301f4381
    domain: humidifier
    entity_id: 363affaee91aeb03abff603b1303a63a
    type: set_mode
    mode: Sleep
mode: single
