id: "night_time"
alias: Дом - Ночное время
description: ""
triggers:
  - entity_id:
      - sensor.system_time_of_day_strict
    to: "23"
    trigger: state
condition: []
action:
  - type: turn_on
    device_id: 0a5bd757648d4752cbe403817b630586
    entity_id: fee8218f970f4a507d14c4ce28cf0fe9
    domain: light
  - action: yeelight.set_mode
    metadata: {}
    data:
      mode: moonlight
    target:
      device_id: fc3c718cfb9df856ba26b49245cc78d2
  - action: light.turn_off
    metadata: {}
    data:
      transition: 3
    target:
      device_id: 96e1548acb880416f78bfe965e06461c
  - action: light.turn_on
    metadata: {}
    data:
      effect: "Fireflies"
    target:
      device_id: f2653fddc378327eff1438e10e5b985d
  - device_id: 663a3c3484f3d8da1a0062e02d20dc98
    domain: humidifier
    entity_id: 07af525659e4d4dd5ea684e196afe896
    type: set_mode
    mode: Strong
  - delay:
      hours: 0
      minutes: 15
      seconds: 0
      milliseconds: 0
  - device_id: 663a3c3484f3d8da1a0062e02d20dc98
    domain: humidifier
    entity_id: 07af525659e4d4dd5ea684e196afe896
    type: set_mode
    mode: Sleep
mode: single
