id: Dining_button_long_push
description: ''
mode: single
trigger:
- platform: state
  entity_id:
  - event.aqara_wireless_mini_switch_t1_knopka
  attribute: event_type
  to: long_press
condition: []
action:
- type: turn_off
  device_id: fc3c718cfb9df856ba26b49245cc78d2
  entity_id: eb97dedd436267e16266b0f44d22ee04
  domain: light
- type: turn_off
  device_id: fc3c718cfb9df856ba26b49245cc78d2
  entity_id: b7959698f19f33fb80b13d707eda1af6
  domain: light
alias: Столовая - выключить свет
