id: Dining_button_two_pushes
description: ''
mode: single
triggers:
  - entity_id:
      - event.aqara_wireless_mini_switch_t1_knopka
    attribute: totalNumberOfPressesCounted
    to: "2"
    trigger: state
condition: []
action:
- type: turn_on
  device_id: fc3c718cfb9df856ba26b49245cc78d2
  entity_id: eb97dedd436267e16266b0f44d22ee04
  domain: light
  brightness_pct: 100
  flash: long
alias: Столовая - включить свет кнопкой
