alias: Столовая - управление светом 2 нажатия
id: dining_button_light_control
description: ""
trigger:
  - platform: state
    entity_id:
      - event.aqara_wireless_mini_switch_t1_knopka
    attribute: event_type
    to: multi_press_2
condition: []
action:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: event.aqara_wireless_mini_switch_t1_knopka
            attribute: totalNumberOfPressesCounted
            above: 1
            below: 3
        sequence:
          - type: turn_on
            device_id: fc3c718cfb9df856ba26b49245cc78d2
            entity_id: eb97dedd436267e16266b0f44d22ee04
            domain: light
            brightness_pct: 100
            flash: long
mode: single
