- id: '1731880267921'
  alias: Система - Установка темы
  description: ''
  triggers:
  - event: start
    trigger: homeassistant
  - event_type: automation_reload
    trigger: event
  - entity_id: binary_sensor.motion_sensor_f68e_light
    trigger: state
  conditions: []
  actions:
  - data:
      name: "{%- if is_state(\"binary_sensor.motion_sensor_f68e_light\", \"off\")
        -%}\n  Metro Purple\n{%- else -%}\n  Metro Red\n{%- endif -%}\n"
      mode: "{%- if is_state(\"binary_sensor.motion_sensor_f68e_light\", \"off\")
        -%}\n  dark\n{%- else -%}\n  light\n{%- endif -%}\n"
    action: frontend.set_theme
  mode: single
  max_exceeded: silent
- id: '1731882472967'
  alias: Система - Установка темы123
  description: ''
  triggers:
  - event: start
    trigger: homeassistant
  - event_type: automation_reload
    trigger: event
  - entity_id: binary_sensor.motion_sensor_f68e_light
    trigger: state
  conditions: []
  actions:
  - data:
      name: "{%- if is_state(\"binary_sensor.motion_sensor_f68e_light\", \"off\")
        -%}\n  'Metro Purple'\n{%- else -%}\n  'Metro Red'\n{%- endif -%}\n"
    action: frontend.set_theme
  mode: single
  max_exceeded: silent
