homeassistant:
  name: Home
  latitude: !env_var SECRET_ZONE_HOME_LATITUDE
  longitude: !env_var SECRET_ZONE_HOME_LONGITUDE
  elevation: !env_var SECRET_ZONE_HOME_ELEVATION
  unit_system: metric
  time_zone: Europe/Moscow
  country: RU

  external_url: !env_var SECRET_EXTERNAL_URL
  internal_url: !env_var SECRET_INTERNAL_URL

  media_dirs:
    local: /media

  # Load packages
  packages: !include config_packages/packages.yaml

  allowlist_external_dirs: !include whitelist_external_dirs.yaml



