
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.0.0/8
    - 192.168.0.0/16
    - ::1

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id

notify:
  - platform: telegram
    name: "mizery"
    chat_id: !secret telegram_chat_id

# Updating config the GitOps way
shell_command:
  update_config: cd /config && git pull

zha_toolkit:

default_config:


input_text:
  secret_pin:
    name: tgid
    initial: !secret telegram_chat_id_str