---
id: bedroom_child_asleep
alias: Спальня - ребенок засыпает
description: "Управление при засыпании ребенка"
mode: single

triggers:
  - trigger: state
    entity_id:
      - input_button.child_asleep

conditions: []

actions:
  - action: media_player.turn_off
    metadata: {}
    data: {}
    target:
      device_id: 316993d587599c46f411c73d2ffbf745
  - type: turn_off
    device_id: f2653fddc378327eff1438e10e5b985d
    entity_id: 48d0339708e6462db98b4dea94c88524
    domain: light
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      device_id:
        - 774e3c5cb748176992f7bc5a59199d95
        - e30a6cb4926e177593271f2c834bb909
        - 96e1548acb880416f78bfe965e06461c
  - if:
      - condition: device
        type: is_off
        device_id: 0a5bd757648d4752cbe403817b630586
        entity_id: fee8218f970f4a507d14c4ce28cf0fe9
        domain: light
    then:
      - type: turn_on
        device_id: 0a5bd757648d4752cbe403817b630586
        entity_id: fee8218f970f4a507d14c4ce28cf0fe9
        domain: light
      - delay:
          hours: 0
          minutes: 0
          seconds: 10
          milliseconds: 0
  - action: yeelight.set_mode
    metadata: {}
    data:
      mode: moonlight
    target:
      device_id: fc3c718cfb9df856ba26b49245cc78d2
  - action: yeelight.set_color_temp_scene
    metadata: {}
    data:
      brightness: 15
      kelvin: 2500
    target:
      device_id: fc3c718cfb9df856ba26b49245cc78d2