---
id: bedroom_child_awake
alias: Спальня - ребенок проснулся
description: "Управление при пробуждении ребенка"
mode: single

triggers:
  - trigger: state
    entity_id:
      - input_boolean.rebenok_spit
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 15
      seconds: 0

conditions: []

actions:
  - action: light.turn_on
    metadata: {}
    data:
      rgb_color:
        - 255
        - 255
        - 255
      brightness_pct: 100
      transition: 3
    target:
      area_id: spalnia
  - type: turn_on
    device_id: 96e1548acb880416f78bfe965e06461c
    entity_id: 0549956679315d6bad7aeaeddec2c435
    domain: light
    brightness_pct: 100
    flash: long