---
id: bedroom_child_asleep
alias: Спальня - ребенок засыпает
description: "Управление при засыпании ребенка"
mode: single

triggers:
  - trigger: state
    entity_id:
      - input_boolean.rebenok_spit
    from: "off"
    to: "on"

conditions: []

actions:
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      area_id: spalnia
  - action: yeelight.set_mode
    metadata: {}
    data:
      mode: moonlight
    target:
      device_id: fc3c718cfb9df856ba26b49245cc78d2
  - action: yeelight.set_color_temp_scene
    metadata: {}
    data:
      brightness: 10
    target:
      device_id: fc3c718cfb9df856ba26b49245cc78d2
  - type: turn_off
    device_id: f2653fddc378327eff1438e10e5b985d
    entity_id: 48d0339708e6462db98b4dea94c88524
    domain: light
  - action: media_player.turn_off
    metadata: {}
    data: {}
    target:
      device_id: 316993d587599c46f411c73d2ffbf745