---
id: bedroom_child_awake
alias: Спальня - ребенок проснулся
description: "Управление при пробуждении ребенка"
mode: single

triggers:
  - trigger: state
    entity_id:
      - input_button.child_awake

conditions: []

actions:
  - if:
      - condition: device
        type: is_off
        device_id: 75739e28167cd8c27f94738c4e62d1b1
        entity_id: 62e676dd0b82493a035a731d979e71c5
        domain: light
    then:
      - type: turn_on
        device_id: 75739e28167cd8c27f94738c4e62d1b1
        entity_id: 62e676dd0b82493a035a731d979e71c5
        domain: light
      - delay:
          hours: 0
          minutes: 0
          seconds: 15
          milliseconds: 0
  - action: yeelight.set_color_temp_scene
    metadata: {}
    data:
      kelvin: 2500
      brightness: 5
    target:
      device_id: 96e1548acb880416f78bfe965e06461c
  - if:
      - condition: device
        type: is_off
        device_id: 0a5bd757648d4752cbe403817b630586
        entity_id: fee8218f970f4a507d14c4ce28cf0fe9
        domain: light
    then:
      - type: turn_on
        device_id: 0a5bd757648d4752cbe403817b630586
        entity_id: fee8218f970f4a507d14c4ce28cf0fe9
        domain: light
      - delay:
          hours: 0
          minutes: 0
          seconds: 15
          milliseconds: 0
  - action: yeelight.set_color_temp_scene
    metadata: {}
    data:
      kelvin: 6500
      brightness: 100
    target:
      device_id: fc3c718cfb9df856ba26b49245cc78d2
  - action: light.turn_on
    metadata: {}
    data:
      transition: 3
      rgb_color:
        - 255
        - 251
        - 0
      brightness_pct: 100
    target:
      device_id:
        - 774e3c5cb748176992f7bc5a59199d95
        - e30a6cb4926e177593271f2c834bb909
  - type: turn_on
    device_id: f2653fddc378327eff1438e10e5b985d
    entity_id: 48d0339708e6462db98b4dea94c88524
    domain: light
    brightness_pct: 100
  - action: media_player.turn_on
    metadata: {}
    data: {}
    target:
      device_id: 316993d587599c46f411c73d2ffbf745
  - delay:
      hours: 0
      minutes: 15
      seconds: 0
      milliseconds: 0
  - action: light.turn_on
    metadata: {}
    data:
      rgb_color:
        - 255
        - 255
        - 255
      brightness_pct: 100
      transition: 3
    target:
      area_id: spalnia
  - type: turn_on
    device_id: 96e1548acb880416f78bfe965e06461c
    entity_id: 0549956679315d6bad7aeaeddec2c435
    domain: light
    brightness_pct: 100
    flash: long