alias: Спальня - управление ночником слева вечером
id: bedroom_evening_nightstand_management_left
description: ""
mode: single
triggers:
  - type: occupied
    device_id: 620530f17357dbdd4f0542c70a5b02b1
    entity_id: d8095bbc750323390fbaee18de59984c
    domain: binary_sensor
    trigger: device
conditions:
  - condition: time
    after: "20:00:00"
    before: "01:00:00"
actions:
  - if:
      - condition: state
        entity_id: input_boolean.rebenok_spit
        state: "on"
    then:
      - action: light.turn_on
        metadata: {}
        data:
          rgb_color:
            - 124
            - 42
            - 0
          brightness_pct: 1
          transition: 3
        target:
          device_id: 774e3c5cb748176992f7bc5a59199d95
    else:
      - action: light.turn_on
        metadata: {}
        data:
          rgb_color:
            - 124
            - 42
            - 0
          brightness_pct: 100
          transition: 3
        target:
          device_id: 774e3c5cb748176992f7bc5a59199d95
  - delay:
      hours: 0
      minutes: 15
      seconds: 0
      milliseconds: 0
  - if:
      - type: is_not_occupied
        condition: device
        device_id: 620530f17357dbdd4f0542c70a5b02b1
        entity_id: d8095bbc750323390fbaee18de59984c
        domain: binary_sensor
    then:
      - action: light.turn_off
        metadata: {}
        data:
          transition: 3
        target:
          device_id: 774e3c5cb748176992f7bc5a59199d95
