alias: Спальня - управление ночником справа вечером
id: bedroom_evening_nightstand_management_right
description: ""
mode: single
triggers:
  - type: occupied
    device_id: 1527a85b199ec815c7238d0b124b6469
    entity_id: d8f06cf75a1594704710dc21a4f101d9
    domain: binary_sensor
    trigger: device
conditions:
  - condition: time
    after: "20:00:00"
    before: "01:00:00"
actions:
  - if:
      - condition: state
        entity_id: input_boolean.rebenok_spit
        state: "on"
    then:
      - action: light.turn_on
        metadata: {}
        data:
          rgb_color:
            - 92
            - 7
            - 0
          brightness_pct: 1
          transition: 3
        target:
          device_id: e30a6cb4926e177593271f2c834bb909
    else:
      - action: light.turn_on
        metadata: {}
        data:
          rgb_color:
            - 90
            - 28
            - 0
          brightness_pct: 100
          transition: 3
        target:
          device_id: e30a6cb4926e177593271f2c834bb909
  - delay:
      hours: 0
      minutes: 15
      seconds: 0
      milliseconds: 0
  - if:
      - type: is_not_occupied
        condition: device
        device_id: 1527a85b199ec815c7238d0b124b6469
        entity_id: d8f06cf75a1594704710dc21a4f101d9
        domain: binary_sensor
    then:
      - action: light.turn_off
        metadata: {}
        data:
          transition: 3
        target:
          device_id: e30a6cb4926e177593271f2c834bb909