---
alias: Спальня - управление ночником справа ночью
id: bedroom_night_nightstand_management_right
description: ""
mode: single
triggers:
  - type: occupied
    device_id: 1527a85b199ec815c7238d0b124b6469
    entity_id: d8f06cf75a1594704710dc21a4f101d9
    domain: binary_sensor
    metadata:
      secondary: false
    trigger: device
conditions:
  - condition: time
    after: "01:00:00"
    before: "05:00:00"
actions:
  - device_id: fb7478e46ebb1c6857c3f498301f4381
    domain: humidifier
    entity_id: 363affaee91aeb03abff603b1303a63a
    type: set_mode
    mode: Strong
  - action: light.turn_on
    metadata: {}
    data:
      rgb_color:
        - 77
        - 34
        - 179
      brightness_pct: 5
      transition: 3
    target:
      device_id: e30a6cb4926e177593271f2c834bb909
  - delay:
      hours: 0
      minutes: 15
      seconds: 0
      milliseconds: 0
  - if:
      - type: is_not_occupied
        condition: device
        device_id: 1527a85b199ec815c7238d0b124b6469
        entity_id: d8f06cf75a1594704710dc21a4f101d9
        domain: binary_sensor
    then:
      - device_id: fb7478e46ebb1c6857c3f498301f4381
        domain: humidifier
        entity_id: 363affaee91aeb03abff603b1303a63a
        type: set_mode
        mode: Constant Humidity
      - action: light.turn_off
        metadata: {}
        data:
          transition: 3
        target:
          device_id: e30a6cb4926e177593271f2c834bb909
