---
id: bedroom_nightstand_right_automatic_on
alias: Спальня - управление светом ночника справа
trigger:
  - platform: state
    entity_id: input_boolean.home_modes_bedtime_mode
    to: "on"

condition:
  - condition: state
    entity_id: binary_sensor.bedroom_bed_occupancy_right
    state: "off"

action:
  - service: scene.turn_on
    data:
      entity_id: scene.bedroom_lights_nightstand_bernd_dimmed
      transition: 2
