title: Security
path: security
id: security
type: custom:grid-layout
layout: !include snippets/layout-3-column.yaml

cards:
  # Header
  - type: heading
    heading_style: title
    heading: Security
    view_layout:
      grid-column: 1/-1

  # Driveway
  - type: vertical-stack
    cards:
      - type: heading
        heading_style: subtitle
        heading: Driveway

      - type: custom:webrtc-camera
        url: doorbell
        entity: camera.gates
        style: '.mode {display: none}'

      # - type: horizontal-stack
      #   cards:
      #     - type: "custom:button-card"
      #       template:
      #         - live_tile_mini
      #       show_name: true
      #       entity: binary_sensor.doorbell_person_occupancy
      #       name: Person detected

      #     - type: "custom:button-card"
      #       template:
      #         - live_tile_with_camera
      #       entity: camera.doorbell_person
      #       name: Last person

  # Rooms
  - type: vertical-stack
    cards:
      - type: heading
        heading_style: subtitle
        heading: Rooms

      - type: "custom:multiple-entity-row"
        entity: binary_sensor.aqara_door_and_window_sensor_t1_dver
        name: Спальня
        icon: mdi:coat-rack
        show_state: false
        entities:
          - entity: binary_sensor.aqara_door_and_window_sensor_t1_dver
            name: Дверь спальни
            icon: true
            state_color: true

          - entity: binary_sensor.aqara_motion_sensor_bedroom_p1_zaniatost
            name: Датчик движения
            icon: true
            state_color: true

      - type: "custom:multiple-entity-row"
        entity: binary_sensor.living_room_door_contact
        name: Living Room
        icon: mdi:sofa
        show_state: false
        entities:
          - entity: binary_sensor.living_room_door_contact
            name: Door
            icon: true
            state_color: true
          - entity: binary_sensor.living_room_window_contact
            name: Window
            icon: true
            state_color: true
          - entity: binary_sensor.living_room_motion_sensor_occupancy
            name: Motion
            icon: true
            state_color: true

      - type: "custom:multiple-entity-row"
        entity: binary_sensor.dining_area_garden_doors_contact
        name: Dining Area
        icon: mdi:table-furniture
        show_state: false
        entities:
          - entity: binary_sensor.dining_area_garden_doors_contact
            name: Garden Doors
            icon: true
            state_color: true
          - entity: binary_sensor.dining_area_motion_sensor_occupancy
            name: Motion
            icon: true
            state_color: true

      - type: "custom:multiple-entity-row"
        entity: binary_sensor.kitchen_motion_sensor_occupancy
        name: Kitchen
        icon: mdi:countertop
        show_state: false
        entities:
          - entity: binary_sensor.kitchen_motion_sensor_occupancy
            name: Motion
            icon: true
            state_color: true

      - type: "custom:multiple-entity-row"
        entity: binary_sensor.utility_room_door_contact
        name: Utility Room
        icon: mdi:washing-machine
        show_state: false
        entities:
          - entity: binary_sensor.utility_room_door_contact
            name: Door
            icon: true
            state_color: true
          - entity: binary_sensor.utility_room_garden_door_contact
            name: Garden door
            icon: true
            state_color: true

      - type: "custom:multiple-entity-row"
        entity: binary_sensor.utility_room_garage_entry_door_contact
        name: Garage
        icon: mdi:car
        show_state: false
        entities:
          - entity: binary_sensor.utility_room_garage_entry_door_contact
            name: Entry door
            icon: true
            state_color: true
          - entity: binary_sensor.garage_door_contact
            name: Garage door
            icon: true
            state_color: true

      - type: "custom:multiple-entity-row"
        entity: binary_sensor.utility_room_garage_entry_door_contact
        name: Attic office
        icon: mdi:desk
        show_state: false
        entities:
          - entity: binary_sensor.attic_office_window_contact
            name: Window
            icon: true
            state_color: true
          - entity: binary_sensor.attic_office_balcony_door_contact
            name: Balcony door
            icon: true
            state_color: true
          - entity: binary_sensor.attic_office_motion_sensor_occupancy
            name: Motion
            icon: true
            state_color: true
