title: Видеонаблюдение
path: security
id: security
type: custom:grid-layout
layout: !include snippets/layout-3-column.yaml

cards:
  # Header
  - type: heading
    heading_style: title
    heading: Видеонаблюдение
    view_layout:
      grid-column: 1/-1

  # Driveway
  - type: vertical-stack
    cards:

      - type: custom:webrtc-camera
        url: gates_hq
        mode:
          - webrtc
          - mse
        name: Ворота
        media: video,audio
        muted: true
        style: '.mode {display: none}'