id: '1724802355139'
alias: Система - Дневное время
description: ''
trigger:
- platform: state
  entity_id:
  - binary_sensor.den
  from: 'off'
  to: 'on'
condition: []
action:
- action: fan.set_preset_mode
  metadata: {}
  data:
    preset_mode: Natural Wind
  target:
    entity_id: fan.dmaker_p45_cfbf_fan
- action: fan.set_percentage
  target:
    entity_id: fan.dmaker_p45_cfbf_fan
  data:
    percentage: 100
- type: turn_on
  device_id: 0a5bd757648d4752cbe403817b630586
  entity_id: fee8218f970f4a507d14c4ce28cf0fe9
  domain: light
mode: single