id: update_config_github_push_event
alias: Система - впитываем пуш из гита
trigger:
- platform: webhook
  webhook_id: update_config
  local_only: false
action:
- service: shell_command.update_config
- service: homeassistant.restart