---
id: system_set_theme
alias: Система - Установка темы
max_exceeded: silent
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reload
  - platform: state
    entity_id: binary_sensor.motion_sensor_f68e_light
action:
  - service: frontend.set_theme
    data:
      name: "Metro Purple"
      mode: |
        {%- if is_state("binary_sensor.motion_sensor_f68e_light", "off") -%}
          light
        {%- else -%}
          dark
        {%- endif -%}