---
trigger:
  - trigger: time_pattern
    hours: /1
action:
  - action: weather.pirateweather
    data:
      type: hourly
    target:
      entity_id: weather.home
    response_variable: hourly
sensor:
  - name: Temperature forecast next hour
    unique_id: temperature_forecast_next_hour
    state: "{{ hourly['weather.home'].forecast[0].temperature }}"
    unit_of_measurement: °C