id: '1724800362490'
alias: Тусклый свет в гостиной
description: ''
trigger:
- platform: state
  entity_id:
  - input_boolean.tusklyi_svet_v_gostinoi
  from: 'off'
  to: 'on'
condition: []
action:
- action: light.turn_on
  metadata: {}
  data:
    kelvin: 2000
    brightness_pct: 10
  target:
    device_id: e4cfc9c939b1bad610e38df9d321b228
- action: light.turn_on
  metadata: {}
  data:
    brightness_pct: 100
    rgb_color:
    - 69
    - 14
    - 89
  target:
    entity_id: light.colorful_ceiling_light_36w_osveshchenie_2
- action: input_boolean.turn_off
  target:
    entity_id:
    - input_boolean.iarkii_svet_v_gostinoi
  data: {}
mode: single
